name: project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  image_picker: ^0.8.7+4
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.1
  firebase_auth_web: ^5.8.13
  js: ^0.6.7 
  google_sign_in: ^6.1.0
  http: ^0.13.6
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
  url_launcher: ^6.2.5
  animated_text_kit: ^4.2.2
  file_picker: ^8.0.7
  intl: ^0.20.2
  flutter_dotenv: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
 
flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-Bold.ttf
          weight: 700

  assets:
    - .env
    - assets/uk_flag.png
    - assets/image.png
    - assets/logo.png
    - assets/google_icon.png
    - assets/facebook_icon.png
    - assets/articles/Blouse.jpg
    - assets/articles/chemise.jpg
    - assets/articles/Pull.jpg
    - assets/articles/Sweat.jpg
